const projects = {
  ragChatbots: { index: '01', title: 'RAG CHATBOTS', art: '$ ./rag-chatbots', detail: 'AI-POWERED<br>CHATBOTS<br>RAG SYSTEMS', mark: 'AI', tags: ['AI', 'RAG', 'CHATBOTS'], description: 'Exploring AI-powered applications and chatbots with retrieval-augmented generation systems.', href: 'https://github.com/antoniovasssss', linkLabel: 'VIEW GITHUB', color: '#aeeeff' },
  fullStackApps: { index: '02', title: 'FULL-STACK APPS', art: '$ ./full-stack-apps', detail: 'NEXT.JS<br>APIS<br>REACT', mark: 'WEB', tags: ['NEXT.JS', 'APIS', 'REACT'], description: 'Developing full-stack applications with modern web technologies and APIs.', href: 'https://github.com/antoniovasssss', linkLabel: 'VIEW GITHUB', color: '#fff5ba' },
  backendAutomation: { index: '03', title: 'BACKEND AUTOMATION', art: '$ ./backend-automation', detail: 'NODE.JS<br>APIS<br>AUTOMATION', mark: 'OPS', tags: ['NODE.JS', 'APIS', 'AUTOMATION'], description: 'Building stronger backend and automation skills for reliable, practical systems.', href: 'https://github.com/antoniovasssss', linkLabel: 'VIEW GITHUB', color: '#d8f5bd' },
  aiLearning: { index: '04', title: 'AI & ML', art: '$ ./ai-learning', detail: 'AI<br>MACHINE LEARNING<br>PYTHON', mark: 'ML', tags: ['AI', 'ML', 'PYTHON'], description: 'Learning artificial intelligence and machine learning through hands-on study and experimentation.', href: 'https://github.com/antoniovasssss', linkLabel: 'VIEW GITHUB', color: '#ffc2bc' }
};
const preview = { index: document.querySelector('#preview-index'), title: document.querySelector('#preview-title'), description: document.querySelector('#preview-description'), art: document.querySelector('#preview-art'), tags: document.querySelector('#tech-tags'), link: document.querySelector('#project-link'), box: document.querySelector('#preview-box') };
document.querySelectorAll('.project-file').forEach((file) => file.addEventListener('click', () => { const project = projects[file.dataset.project]; document.querySelectorAll('.project-file').forEach((item) => item.classList.toggle('selected', item === file)); preview.index.textContent = project.index; preview.title.textContent = project.title; preview.description.textContent = project.description; preview.art.innerHTML = `<b>${project.art}</b><span>${project.detail}</span><strong>${project.mark}</strong>`; preview.art.style.background = project.color; preview.tags.innerHTML = project.tags.map((tag) => `<span>${tag}</span>`).join(''); preview.link.href = project.href; preview.link.textContent = project.linkLabel; preview.box.animate([{ backgroundColor: '#7a1f35' }, { backgroundColor: '#ebebea' }], { duration: 380, easing: 'ease-out' }); }));
const links = [...document.querySelectorAll('.nav-link[href^="#"]')]; const sections = links.map((link) => document.querySelector(link.getAttribute('href'))); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) links.forEach((link) => link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}`)); }), { rootMargin: '-35% 0px -55% 0px' }); sections.forEach((section) => observer.observe(section));
links.forEach((link) => link.addEventListener('click', () => links.forEach((item) => item.classList.toggle('active', item === link))));
