const projects = {
  projectOne: { index: '01', title: 'PROJECT ONE', art: '$ ./project-one', detail: 'YOUR<br>PROJECT<br>SUMMARY', mark: '01', tags: ['TOPIC', 'TOPIC', 'TOPIC'], description: 'Replace this with a short, honest description of your first project and the outcome it created.', href: 'https://github.com/your-github-username/project-one', linkLabel: 'VIEW PROJECT', color: '#aeeeff' },
  projectTwo: { index: '02', title: 'PROJECT TWO', art: '$ ./project-two', detail: 'YOUR<br>PROJECT<br>SUMMARY', mark: '02', tags: ['TOPIC', 'TOPIC', 'TOPIC'], description: 'Replace this with a short, honest description of your second project and the skills it demonstrates.', href: 'https://github.com/your-github-username/project-two', linkLabel: 'VIEW PROJECT', color: '#fff5ba' },
  projectThree: { index: '03', title: 'PROJECT THREE', art: '$ ./project-three', detail: 'YOUR<br>PROJECT<br>SUMMARY', mark: '03', tags: ['TOPIC', 'TOPIC', 'TOPIC'], description: 'Replace this with a short, honest description of a project you are proud to discuss in an interview.', href: 'https://github.com/your-github-username/project-three', linkLabel: 'VIEW PROJECT', color: '#d8f5bd' },
  projectFour: { index: '04', title: 'PROJECT FOUR', art: '$ ./project-four', detail: 'YOUR<br>PROJECT<br>SUMMARY', mark: '04', tags: ['TOPIC', 'TOPIC', 'TOPIC'], description: 'Replace this with a concise note about another project, experiment, or community contribution.', href: 'https://github.com/your-github-username/project-four', linkLabel: 'VIEW PROJECT', color: '#ffc2bc' }
};
const preview = { index: document.querySelector('#preview-index'), title: document.querySelector('#preview-title'), description: document.querySelector('#preview-description'), art: document.querySelector('#preview-art'), tags: document.querySelector('#tech-tags'), link: document.querySelector('#project-link'), box: document.querySelector('#preview-box') };
document.querySelectorAll('.project-file').forEach((file) => file.addEventListener('click', () => { const project = projects[file.dataset.project]; document.querySelectorAll('.project-file').forEach((item) => item.classList.toggle('selected', item === file)); preview.index.textContent = project.index; preview.title.textContent = project.title; preview.description.textContent = project.description; preview.art.innerHTML = `<b>${project.art}</b><span>${project.detail}</span><strong>${project.mark}</strong>`; preview.art.style.background = project.color; preview.tags.innerHTML = project.tags.map((tag) => `<span>${tag}</span>`).join(''); preview.link.href = project.href; preview.link.textContent = project.linkLabel; preview.box.animate([{ backgroundColor: '#7a1f35' }, { backgroundColor: '#ebebea' }], { duration: 380, easing: 'ease-out' }); }));
const links = [...document.querySelectorAll('.nav-link[href^="#"]')]; const sections = links.map((link) => document.querySelector(link.getAttribute('href'))); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) links.forEach((link) => link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}`)); }), { rootMargin: '-35% 0px -55% 0px' }); sections.forEach((section) => observer.observe(section));
links.forEach((link) => link.addEventListener('click', () => links.forEach((item) => item.classList.toggle('active', item === link))));
