const projects = {
  ragDocumentSearch: { index: '01', title: 'RAG DOCUMENT SEARCH', art: '$ ./rag-search-app', detail: 'DOCUMENT<br>SEARCH<br>WITH RAG', mark: 'RAG', tags: ['PYTHON', 'LANGGRAPH', 'FAISS'], description: 'A RAG application that turns curated web pages into a question-and-answer experience, showing retrieved source excerpts in a Streamlit interface.', href: 'https://github.com/antoniovasssss/rag-search-app', linkLabel: 'VIEW REPOSITORY', color: '#aeeeff' },
  miniLlm: { index: '02', title: 'MINI LLM', art: '$ ./simple-llm', detail: 'TEXT<br>GENERATION<br>DEMO', mark: 'LLM', tags: ['PYTHON', 'TRANSFORMERS', 'DISTILGPT-2'], description: 'A hands-on DistilGPT-2 text-generation demo with batch, interactive, and tokenizer-explainer modes using Hugging Face Transformers.', href: 'https://github.com/antoniovasssss/simple-llm', linkLabel: 'VIEW REPOSITORY', color: '#fff5ba' },
  aiSearchAgent: { index: '03', title: 'AI SEARCH AGENT', art: '$ ./ai-search-agent', detail: 'WEB SEARCH<br>WIKIPEDIA<br>RESEARCH', mark: 'AI', tags: ['PYTHON', 'LANGCHAIN', 'CLAUDE'], description: 'A command-line research agent that uses LangChain, Claude, DuckDuckGo, and Wikipedia to produce structured, source-aware research responses.', href: 'https://github.com/antoniovasssss/ai-search-agent', linkLabel: 'VIEW REPOSITORY', color: '#d8f5bd' },
  parisTravelAgent: { index: '04', title: 'PARIS TRAVEL AI AGENT', art: '$ ./travel-ai-agent', detail: 'PARIS<br>TRAVEL<br>ASSISTANT', mark: 'PAR', tags: ['PYTHON', 'GRADIO', 'OPENAI'], description: 'A focused Paris trip-planning chat app with an OpenAI model and Gradio UI, designed to stay on-topic and be transparent about uncertainty.', href: 'https://github.com/antoniovasssss/travel-ai-agent', linkLabel: 'VIEW REPOSITORY', color: '#ffc2bc' }
};
const preview = { index: document.querySelector('#preview-index'), title: document.querySelector('#preview-title'), description: document.querySelector('#preview-description'), art: document.querySelector('#preview-art'), tags: document.querySelector('#tech-tags'), link: document.querySelector('#project-link'), box: document.querySelector('#preview-box') };
document.querySelectorAll('.project-file').forEach((file) => file.addEventListener('click', () => { const project = projects[file.dataset.project]; document.querySelectorAll('.project-file').forEach((item) => item.classList.toggle('selected', item === file)); preview.index.textContent = project.index; preview.title.textContent = project.title; preview.description.textContent = project.description; preview.art.innerHTML = `<b>${project.art}</b><span>${project.detail}</span><strong>${project.mark}</strong>`; preview.art.style.background = project.color; preview.tags.innerHTML = project.tags.map((tag) => `<span>${tag}</span>`).join(''); preview.link.href = project.href; preview.link.textContent = project.linkLabel; preview.box.animate([{ backgroundColor: '#7a1f35' }, { backgroundColor: '#ebebea' }], { duration: 380, easing: 'ease-out' }); }));
const links = [...document.querySelectorAll('.nav-link[href^="#"]')]; const sections = links.map((link) => document.querySelector(link.getAttribute('href'))); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) links.forEach((link) => link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}`)); }), { rootMargin: '-35% 0px -55% 0px' }); sections.forEach((section) => observer.observe(section));
links.forEach((link) => link.addEventListener('click', () => links.forEach((item) => item.classList.toggle('active', item === link))));
